### ISSUE TITLE
Updating somebody's account from the Admin panel

### ISSUE THREAD

**Issue by Lme999** [fbatroni/passwordmanager#73]
**Describe the bug**
When the admin tries to update a users email, it does not check if the email is already taken.
In addition to that, it does not display the user's updated credentials after it is updated.

**To Reproduce**
1. Go to admin panel, click view on a normal user.
2. Update the user's email to a taken email (an example being the admin's email)
3. Click save

**Expected behavior**
Should give an error here saying the email is taken.

**Comment by fbatroni** [comment]
fixed
